updating sdk  and documentation
tago-io/analysis-example-createDevice pull request #3
Opened 2023-07-14 18:25 UTC by rafaelTelesS

## What does PR do?

The TagoIO Sdk has been updated to work with the new access rule system for analysis. This system allows you to control who can access your analysis, what actions they can perform, and under what conditions. To use the new system, you need to update your Sdk version and follow the documentation on how to create and manage access rules. 

## Type of alteration

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [x] Documentation update

2023-07-17 12:19 UTC, Freddyminu approved these changes

2023-09-01 08:49 UTC, vitorfdl requested changes

2023-09-01 08:49 UTC, vitorfdl commented on analysis.js
> +  Resources.devices.sendDeviceData(scope[0].device, { variable: "validation", value: "Device succesfully created!", metadata: { type: "success" } });
Do not use scope[0].device as parameter. Prefer to have it on a variable, so user can better understand the code.

const deviceID = scope[0].device;

2024-04-29 13:46 UTC, vitorfdl approved these changes

2024-04-29 13:46 UTC, merged